files:
  image: ubuntu
  volumes:
    - ./vendor:/app/vendor
    - ./dbdata:/var/lib/postgresql/data/

db:  
  image: "pywebdesign/postgis"
  volumes_from:
    - files
  expose:
    - 5432

web:  
  build: .
  command: bundle exec rails server -b 0.0.0.0
  volumes:
    - .:/app
  volumes_from:
    - files
  ports:
    - "3000:3000"
  links:
    - db
    - files
